doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '14'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Domain\Product:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/UserInterface/Resources/config/doctrine/Product'
                prefix: 'App\Domain\Product'

            App\Domain\User:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/UserInterface/Resources/config/doctrine/User'
                prefix: 'App\Domain\User'

            App\Domain\Order:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/UserInterface/Resources/config/doctrine/Order'
                prefix: 'App\Domain\Order'

            App\Domain\OrderItem:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/UserInterface/Resources/config/doctrine/OrderItem'
                prefix: 'App\Domain\OrderItem'