App\Domain\Product\Product:
    type: entity
    table: products
    id:
        id:
            type: string
            column: id
            length: 100
    
    fields:
        name:
            type: string
            column: name
            nullable: false
            length: 100

        ingredients:
            type: text
            column: ingredients
            nullable: false
            length: 250
        
        price:
            type: float
            column: price
            nullable: false
