App\Domain\User\User:
    type: entity
    table: users
    id:
        id:
            type: integer
            column: id
            nullable: false
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            column: email
            nullable: false
            unique: true
            length: 32
            options:
                fixed: true
                comment: User's email addres

        username:
            type: string
            column: name
            nullable: false
            length: 60

        password:
            type: string
            column: password
            nullable: false
            length: 100

        roles:
            type: array
            nullable: false
            column: roles
